Dockerfile
docker-compose.yml

#11 
`docker-compose up -d` 명령어를 터미널에 작성하시면, 이미지 빌드와 컨테이너 띄우기를 할 수 있습니다. 
`docker-compose down` 명령어로 컨테이너를 내릴 수 있습니다.
---
**<유의점 : 에러 발생 가능 지점>**
1. window 사용 팀원들 : **gradlew 개행모드 LF**로 바꾸셔야합니다.
https://lightning-shell-5dc.notion.site/bin-sh-gradlew-bin-sh-M-bad-interpreter-No-such-file-or-directory-1d0ea008b61c80d6b82eee0192f2d1de?source=copy_link
2. **gradle-wrapper의 부재**
`.gitignore` 을 통해서 모든 `.jar` 을 제외하고 있어서, `gradle-wrapper.jar` 파일이 없을 확률이 높습니다. → gradle을 PC에 설치하거나, 새 프로젝트를 만들어서 mopl 프로젝트 내부 `gradle/wrapper/` 하위에 `gradle-wrapper.jar` 를 복사 붙여넣기 하여 넣어주십쇼.
---
**<Check!!>**
1. 현재는 도커 컨테이너를 띄우기 위해 애플리케이션 build할 때 test를 꺼뒀습니다.
2. kafka, redis 도입 후 얘기가 오가면 Docker-compose.yml에도 kafka, redis 를 띄우는 코드를 추가하여 리팩토링하겠습니다.
3. `.env`, `application-dev.yaml` 은 노션에 업로드 해놓겠습니다.
4. 프론트코드와 연결 이전 초기 세팅 …

chore: Dockerfile, docker-compose.yml 을 통한 도커 테스트 초기 환경 세팅

---

build.gradle
src/main/java/team03/mopl/common/config/WebSocketConfig.java
src/main/java/team03/mopl/domain/chat/controller/ChatMessageController.java
src/main/java/team03/mopl/domain/chat/controller/ChatRoomController.java
src/main/java/team03/mopl/domain/chat/dto/SystemMessageDto.java
src/test/java/team03/mopl/common/config/TestSecurityConfig.java
src/test/java/team03/mopl/domain/chat/controller/ChatMessageControllerTest.java
src/test/java/team03/mopl/domain/chat/controller/ChatMessageControllerWebSocketTest.java
src/test/java/team03/mopl/domain/chat/controller/ChatRoomControllerTest.java
src/test/java/team03/mopl/domain/chat/handler/ChatMessageFrameHandler.java
src/test/java/team03/mopl/domain/chat/handler/TestStompSessionHandler.java

- #41 
- 개발 편의성을 위하여 백엔드 파일에서 제거 
- 별도 레포지토리에서 작업할 예정
- Controller 단위 테스트 코드 구현
- WepSocket + Stomp 로 Controller 구현
- 단일 조회 pathVariable 명시 
- 컨트롤러 단위 테스트 OAuth2 관련 config 제외
- 테스트를 위한 의존성 추가
- WebSocket 연결 테스트 구현
- 테스트 시 Security와 독립 되도록 TestSecurityConfig 추가
- [[Spring] 스프링부트 테스트를 위한 의존성과 어노테이션, 애플리케이션 컨택스트 캐싱(@SpringBootTest, @WebMvcTest, @DataJpaTest)](https://mangkyu.tistory.com/242)
- https://docs.spring.io/spring-framework/docs/4.3.x/spring-framework-reference/html/websocket.html#websocket-stomp-testing
- https://docs.spring.io/spring-boot/reference/using/auto-configuration.html#using.auto-configuration
- [Spring boot 3.5.3 공식문서](https://docs.spring.io/spring-framework/reference/web/websocket/stomp/testing.html#page-title)
- …

feat: 실시간 시청방 내 채팅 시스템 구현

---

src/main/java/team03/mopl/common/exception/ErrorCode.java
src/main/java/team03/mopl/domain/content/controller/ContentController.java
src/main/java/team03/mopl/domain/content/service/ContentService.java
src/main/java/team03/mopl/domain/content/service/ContentServiceImpl.java
src/test/java/team03/mopl/domain/content/controller/ContentControllerTest.java
src/test/java/team03/mopl/domain/content/integration/ContentIntegrationTest.java
src/test/java/team03/mopl/domain/content/service/ContentServiceImplTest.java

- #59 
1. 단순 컨텐츠 전체 조회
단순하고 Service, Repository 쪽에 특별한 로직이 많이 들어가지 않으므로 클라이언트 측에 데이터를 잘 보내는지만 확인하기 위해 컨트롤러 단위 테스트만 진행
3. 단일 컨텐츠 조회
존재 여부에 따라서 분기(1. 있음 → 콘텐츠 반환, 2 없음 → 에러)가 발생하므로
로직이 들어가는 Service 단위 테스트 작성, 예외 핸들링이 잘 되고 있는지 파악하기 위해 통합 테스트 진행
[@PathVariable("이름 넣는 거 까먹어서 생겼던 오류")](https://lightning-shell-5dc.notion.site/message-Name-for-argument-of-type-java-util-UUID-not-specified-and-parameter-name-information-n-225ea008b61c80fc8af4ea4f6f9d8dc2?source=copy_link)

feat: 단순 전체 컨텐츠 조회와 단일 컨텐츠 조회 구현

---

init/schema.sql
src/main/java/team03/mopl/domain/chat/entity/ChatMessage.java
src/main/java/team03/mopl/domain/chat/entity/ChatRoom.java
src/main/java/team03/mopl/domain/chat/entity/ChatRoomParticipant.java

- chat_rooms 필드 추가( current_time, is_playing, video_state_updated_at) 및
테이블명 watch_rooms로 변경
- chat_messages → watch_room_messages로 테이블명 변경
- chat_room_participants → watch_room_participants로 테이블명 변경
- User 엔티티 profile_image 필드 추가
- #69 
제가 제거 머지하는걸 깜박해서 이전 PR 내용이 같이 들어갔었습니다. 수정된 부분만 들어가게 하고싶어서 열었다 닫았다 했습니다. 헷갈리게 해드렸다면 죄송합니다. 😢

docs: chat -> watch 변경, 유저 profile_image 필드 추가로 인한 schema.sql 수정

---

src/main/java/team03/mopl/domain/chat/entity/ChatRoom.java
src/main/java/team03/mopl/domain/curation/entity/Keyword.java
src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
src/test/java/team03/mopl/domain/curation/CurationControllerTest.java
src/test/java/team03/mopl/domain/curation/CurationServiceImplTest.java

- #62 
Close #62 
1. curation domain에 대한 service, controller 테스트 코드 추가
2. keyword entity에서 생성자 대신 builder 패턴 사용
- curationServiceImpl 코드 수정
3. ChatRoom entity 필드 수정
- currentTime 필드가 schema와 일치하지 않아 playTime으로 변경
- curation 배치 처리

feat: curation service test, controller test 추가

---

src/main/java/team03/mopl/domain/follow/controller/FollowController.java
src/main/java/team03/mopl/domain/follow/dto/FollowResponse.java
src/main/java/team03/mopl/domain/follow/entity/Follow.java
src/main/java/team03/mopl/domain/follow/service/FollowService.java
src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java
src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
src/test/java/team03/mopl/domain/follow/controller/FollowControllerTest.java

- 팔로워/팔로우 조회 시 user id가 없음
- id가 없어 팔로우 요청, 팔로우 취소, 플레이리스트 보기 등 기능을 만들기 어려워 id 필드를 추가하였습니다.
- FollowService 의 getFollowing(), getFollowers() 메서드 반환값 List<UserResponse>에서 List<FollowResponse> 로 변경
- 테스트 코드에도 DTO 적용
- id 필드로 해당 유저의 상세 정보를 불러올 수 있게되었습니다.
- 팔로우 요청 및 팔로우 취소도 가능해졌습니다.
(관리자로 로그인한 상태 - 플레이리스트는 더미입니다.)
(내 팔로우 목록에서 1233 유저의 프로필을 클릭해 상세 프로필 페이지로 이동) 
(팔로우 이전)
(팔로우 이후 - 현재 프론트엔드 언팔로우 기능 수정중)

fix: follow 관련 조회 기능 응답 DTO 수정

---

.github/workflows/deploy.yml
.github/workflows/test.yml
.gitignore
Dockerfile
ecs/task-definition.json
src/main/resources/application-prod.yaml

- #84 
**<아키텍처 구성>**
1. 소스 코드: GitHub Repository
2. CI/CD: GitHub Actions
- main 브랜치 Push 시 CD(빌드, 배포) 파이프라인 자동 실행
3. 컨테이너 이미지 저장소: Amazon ECR
- GitHub Actions에서 빌드된 Docker 이미지를 버전별로 저장
4. 보안 및 인증: AWS IAM
- GitHub Actions와 AWS 간의 안전한 인증을 위해 OIDC(OpenID Connect) 방식 사용
5. 네트워크 관문: Amazon ALB
- 인터넷 사용자의 HTTP:80 트래픽을 수신하는 단일 진입점 역할
- 고정된 DNS 주소를 제공하여 안정적인 서비스 엔드포인트 역할 수행
- localhost:8080 을 대체하기 위해 도입
6. 컴퓨팅 및 배포: Amazon ECS on EC2
- ECS: 컨테이너 오케스트레이션 및 배포 자동화 관리
- EC2: t2.micro 인스턴스 1대가 실제 Docker 컨테이너를 실행
7. 데이터베이스: Amazon RDS (Relational Database Service)
- PostgreSQL 데이터베이스
8. 네트워크 보안: Amazon VPC
- 보안 그룹:
- ALB → EC2 (80 포트) 로의 트래픽만 허용
- EC2 → RDS (5432 포트) 로의 트래픽만 허용
------
**이슈에 적었던 것에서 달라진 부분은 ALB(로드밸런서) 도입입니다!**
application.yaml에 이런 …

Chore: CD 워크 플로우 작성

---

src/main/java/team03/mopl/domain/watchroom/controller/WatchRoomController.java
src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomCreateRequest.java
src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomDto.java
src/main/java/team03/mopl/domain/watchroom/entity/WatchRoom.java
src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java

- 시청방 조회시 방장 이름을 보여주기 위해 id필드 뿐만 아니라 name 필드도 필요해짐.
- watchRoom ownerId 필드를 User객체 Owner로 변경
- watchRoomDto에 ownerName 필드, createdAt 추가

fix: watchRoom ownerId 필드를 User객체로 변경

---

src/main/java/team03/mopl/common/exception/ErrorCode.java
src/main/java/team03/mopl/common/exception/curation/KeywordDeleteDeniedException.java
src/main/java/team03/mopl/domain/curation/controller/CurationController.java
src/main/java/team03/mopl/domain/curation/service/CurationService.java
src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java

- keyword를 등록한 사용자가 아니면 삭제할 수 없도록

refactor: keyword delete 메서드에 @AuthenticationPrincipal 추가

---

src/main/java/team03/mopl/common/exception/ErrorCode.java
src/main/java/team03/mopl/common/exception/review/DuplicateReviewException.java
src/main/java/team03/mopl/domain/review/repository/ReviewRepository.java
src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java

- #97 
@yudility 
- user가 해당 content에 이미 리뷰를 작성했으면 DuplicateReviewException 발생

fix: 리뷰 중복 작성에 대한 예외처리 추가

---

src/main/java/team03/mopl/domain/curation/controller/CurationController.java
src/main/java/team03/mopl/domain/curation/service/CurationService.java
src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
src/test/java/team03/mopl/domain/curation/CurationControllerTest.java
src/test/java/team03/mopl/domain/curation/CurationServiceImplTest.java

- Keyword 별 콘텐츠 조회시 Cotent 엔티티 반환하던 것을 ContentDto 반환하도록 수정
- 테스트 코드 수정
- 컨트롤러 및 서비스 반환값 수정
테스트 통과가 안되네요 ㅠㅠ 
- CurationControllerTest
- CurationServiceImplTest

fix: Keyword 별 콘텐츠 조회시 ContentDto 반환하도록 수정

---

src/main/java/team03/mopl/storage/S3ProfileStorage.java

- 읽기 열기
- 버킷 정책 이미지만 읽을 수 있게 정책 설정했습니다.

fix: s3 읽기 설정

---

src/main/java/team03/mopl/domain/playlist/dto/PlaylistDto.java

- #129 
Close #129 
- playlistDto 필드 변경 (entity -> dto)
변경 전
```
List<Content> contents,
List<Subscription> subscribers
```
변경 후
```
List<ContentDto> contents,
List<SubscriptionDto> subscribers
```

fix: playlistDto 변경

---

src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
src/main/java/team03/mopl/domain/notification/controller/NotificationController.java
src/main/java/team03/mopl/domain/notification/dto/NotificationDto.java
src/main/java/team03/mopl/domain/notification/repository/NotificationRepository.java
src/main/java/team03/mopl/domain/notification/service/NotificationService.java
src/main/java/team03/mopl/domain/notification/service/NotificationServiceImpl.java
src/test/java/team03/mopl/domain/follow/controller/FollowControllerTest.java
src/test/java/team03/mopl/domain/notification/controller/NotificationControllerTest.java
src/test/java/team03/mopl/domain/notification/service/NotificationServiceImplTest.java

- #128 
알림 삭제 로직 구현했습니다.
- 알림 ID를 통해 단일 삭제
- 유저 ID를 통해 읽은 알림 단체 삭제
-  followingControllerTest, NotificationServiceImplTest 테스트 코드 수정

feature: 알림 삭제 로직 구현 및 테스트 코드 수정

---

init/schema.sql

- 다국어 정렬 문제로 문자열 정렬 규칙 집합(Collation) 변경 en_US.utf8 -> ko_KR.utf8
```
CREATE TABLE "contents"
(
"id"               UUID PRIMARY KEY                  NOT NULL,
"title"            VARCHAR(255)                      NOT NULL,
"title_normalized" VARCHAR(255) COLLATE "ko_KR.utf8" NOT NULL, # 여기 이렇게
--  "title_normalized" VARCHAR(255) NOT NULL,
"data_id"          varchar(255)                      NULL,
"description"      TEXT                              NULL,
"content_type"     VARCHAR(50)                       NOT NULL,
"release_date"     TIMESTAMP                         NOT NULL,
"avg_rating"       DECIMAL(3, 2)                     NULL CHECK (avg_rating >= 0.0 AND avg_rating <= 5.0),
"created_at"       TIMESTAMP DEFAULT now()           NOT NULL,
"url"              TEXT …
```

chore: 다국어 정렬 문제로 문자열 정렬 규칙 집합(Collation) 변경

---

src/main/java/team03/mopl/domain/curation/entity/KeywordContent.java

- keywordContent 엔티티에 @EntityListeners 어노테이션 추가

fix: keywordContent @EntityListeners 추가

---

src/main/java/team03/mopl/domain/subscription/Subscription.java
src/main/java/team03/mopl/domain/subscription/service/SubscriptionServiceImpl.java

- subscribe()를 사용하여도 Subscription 엔티티가 생성되지 않는 이슈 
- Subscription 엔티티 @EntityListeners 추가
- subscribe() 메서드의 @ Transactional(readOnly = true) -> @ Transactional로 수정

fix: Subscription 엔티티 @EntityListeners 추가 및 생성 메서드 트랜젝션 수정

---

build.gradle
docker-compose.yml

- #172 
Redis, Kafka 컨테이너를 docker compose에 추가 했습니다.
**<주의사항>**
1. Kafka를 현재 이용하고 있지 않을시
Kafka의 경우 zookeeper와 함께 사용할 때의 크기가 더 나가서(1gb에 가까움), kRaft 모드로 등록해놨습니다.
그럼에도 불구하고 Kafka의 이미지 자체의 크기가 771.11MB 정도 하기 때문에, 현재 사용하지 않으시면 검색:kafka해서 관련 부분 주석 처리한 후 사용하시길 권장드립니다.
2. application-dev.yaml 업데이트
수정된 환경 설정이 없을시 애플리케이션과 연동이 어렵습니다. 참고하십쇼!
---
언제 했는지 기억도 안나지만 (수정일자를 보니 06.25네요) 옛날에 이 두 개에 대해서 짧게 공부한 기록이있어 남기고 갑니다
<레디스>
https://lightning-shell-5dc.notion.site/Redis-21bea008b61c80939211cfb3c167dd26?source=copy_link
<카프카>
https://lightning-shell-5dc.notion.site/Kafka-21bea008b61c80c5946dd0e12cb95bc1?source=copy_link

chore: docker-compose.yml에 Redis, Kafka 컨테이너 추가

---

init/schema.sql
src/main/java/team03/mopl/domain/content/Content.java
src/main/java/team03/mopl/domain/content/batch/launcher/SportsJobScheduler.java
src/main/java/team03/mopl/domain/content/batch/launcher/TmdbJobScheduler.java
src/main/java/team03/mopl/domain/content/batch/sports/SportsApiProcessor.java
src/main/java/team03/mopl/domain/content/batch/sports/SportsItemDto.java
src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbApiProcessor.java
src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbApiReader.java
src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbItemDto.java
src/main/java/team03/mopl/domain/content/dto/ContentDto.java
src/test/java/team03/mopl/domain/content/repository/ContentRepositoryImplTest.java

- #178 
**초기 적재를 통해 youtube_url, thumnail_url 적재 확인**
1. ContentType: MOVIE의 youtube_url, thumnail_url 적재
2. ContentType: SPORTS의 youtube_url, thumnail_url 적재
3. ContentType: TV의 youtube_url, thumnail_url 적재
-----
**1. TMDB**
유튜브 URL 없으면 적재x → 주기적 적재할 때 Item이 총 0개 적재되는 문제 발생
(이전) movie나 tv의 주기적 적재를 만들면서 고민을 많이 했던 게 movie나 tv는 매일매일 컨텐츠가 뜨는 컨텐츠(특히 다들 알음알음 알 정도면)들이 아니기도 해서, 매일 적재로도 들고올 수 있는 데이터가 적겠다~ 생각은 했으나, 5~10개 정도는 적재되어 유지했습니다.
(변경된 부분) 그러나 유튜브 URL 없으면 적재하지 않는 로직을 추가하니 Item이 하나도 적재 되지 않아  →→→→
(현재) TMDB의 경우 “매일”이 아닌 “금요일” 새벽 5시에 적재되는 것으로 변경했습니다.
- TV의 경우 일주일 전부터 지금까지 당일 방영한 것을 적재
- MOVIE는 “현재 상영 중” 이므로 유지시켰습니다.
2025년 7월 15일 기준으로 일주일 전까지 적재해봤는데 20개 적재되는 것 확인했습니다!
그외 좋은 생각이 있다면 공유해주세요!
**2. Sports**
한국시각 새벽 12시 → 4시로 변경
- [] 테스트 코드를 통과했나요?

feature: 컨텐츠 썸네일/YouTube URL 컬럼 추가 및 적재 로직 개선

---

src/main/resources/application-prod.yaml

- #191 
**1. application-prod.yaml에 redis 관련 설정을 추가했습니다.
2. mopl.env를 업데이트 했습니다.(→ 아직 S3 버킷에는 업데이트 되어있지 않은 상태)
3. AWS에서 ElastiCache 클라스터 생성 완료**
Valkey는 AWS에서 앞으로 주력으로 지원 Redis 호환 오픈소스입니다.(Redis를 그대로 포크해옴)
**4. mopl03-team 계정에 ElastiCache 관련 권한을 부여해뒀습니다.**
---
https://lightning-shell-5dc.notion.site/Redis-232ea008b61c8090a821dca65aa67298?pvs=74
ElastiCache에 Redis 서버를 띄우면서 선택의 이유나 과정을 메모해둔 문서입니다.
캐시 노드 유형을 선택하기 위해 만들어둔 **장표**가 있으니, 궁금하실 때 확인해보시라고 노션 문서 링크 추가 업로드하고 갑니다! (물론 글이 많은 만큼 질문을 하셔도 언제나 OK)

chore: application-prod.yaml redis 관련 환경 설정 추가

---

init/schema.sql
src/main/java/team03/mopl/common/config/AsyncConfig.java
src/main/java/team03/mopl/common/exception/ErrorCode.java
src/main/java/team03/mopl/common/exception/InvalidCursorFormatException.java
src/main/java/team03/mopl/common/exception/InvalidPageSizeException.java
src/main/java/team03/mopl/common/exception/curation/ContentRatingUpdateException.java
src/main/java/team03/mopl/common/exception/curation/InvalidScoreRangeException.java
src/main/java/team03/mopl/domain/content/batch/sports/SportsBatchConfig.java
src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbBatchConfig.java
src/main/java/team03/mopl/domain/content/repository/ContentRepository.java
src/main/java/team03/mopl/domain/content/service/ContentServiceImpl.java
src/main/java/team03/mopl/domain/curation/CurationBatchConfig.java
src/main/java/team03/mopl/domain/curation/CurationJobListener.java
src/main/java/team03/mopl/domain/curation/controller/CurationController.java
src/main/java/team03/mopl/domain/curation/dto/ContentWithScoreDto.java
src/main/java/team03/mopl/domain/curation/dto/CursorPageRequest.java
src/main/java/team03/mopl/domain/curation/entity/KeywordContent.java
src/main/java/team03/mopl/domain/curation/repository/KeywordContentRepository.java
src/main/java/team03/mopl/domain/curation/service/CurationService.java
src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
src/test/java/team03/mopl/domain/curation/CurationControllerTest.java
src/test/java/team03/mopl/domain/curation/CurationServiceImplTest.java

- #184 
Close #184 
1. curation에 cursor pagination 추가
2. 콘텐츠 데이터 적재 작업 후 큐레이션 처리하도록 event listener 생성
3. keyword와의 점수 계산 비동기 처리

refactor: curation pagination, 비동기, event 처리

---

src/main/java/team03/mopl/domain/review/entity/ReviewEvent.java
src/main/java/team03/mopl/domain/review/event/ReviewEvent.java
src/main/java/team03/mopl/domain/review/event/ReviewEventHandler.java
src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java
src/test/java/team03/mopl/domain/review/ReviewServiceImplTest.java

- #194 
Close #194 
- review create, update, delete 시 content의 평균 평점 자동으로 계산하도록 event 생성

refactor: 리뷰 생성, 수정, 삭제 시 content avgRating 점수 계산 event 생성

---

src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomInfoDto.java
src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java

- 프론트엔드에서 content id와 추가 정보 필요로 하여 contentDto를 추가함
- 시청방 정보 DTO에 ContentDto 추가

fix: 시청방 정보 DTO에 ContentDto 추가

---

src/main/java/team03/mopl/common/util/CursorCodecUtil.java
src/main/java/team03/mopl/domain/content/service/ContentServiceImpl.java
src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
src/test/java/team03/mopl/domain/content/service/ContentServiceImplTest.java
src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java

- #216 
1.  커서 페이지네이션에서 사용하는 디코더와 인코더를 공통 유틸로 분리했습니다.
2. 관련 테스트를 수정했습니다.
3. 코드 전반에 생긴 주석은 리뷰 이후 삭제 또는 수정하여 머지하겠습니다!
@yudility 테스트 부분 확인하고 리뷰 달아주시면, 말씀해주신 방향대로 수정하겠습니다!
----
유틸로 분리하며 1. 제네릭 또는 object 파라미터 사용 / 2. Watchroom과 Content 도메인의 DTO가 인터페이스 사용 → 파라미터에서 해당 인터페이스 받기 / 3. 메서드 오버로딩하여 분리 → 각 메서드에서 WatchroomDto, ContentDto를 받기
세 가지 방식을 고민했는데,
1번째는 가독성과 런타임에 단점으로 넘기고
2번쨰, 3번째 중에서는
1. 여러 개의 도메인 중 두 가지 도메인에서만 사용: Watchroom과 Content 서비스에서만 사용하는 인/디코더
2. 도메인별 관례 다름: sortBy를 lower <-> upper로 각각 비교함 
을 생각하여 3번째 방법을 택했습니다.
lower, upper는 통일하면 되는 문제지만 혹시나 제가 체크하지 못하는 문제가 있을까봐 우선 통일하지 않았습니다. + (통일해도 담당자인 유진님이 한 번 체크하시고 논의한 후에 통일하는 게 맞다고 생각해서!! 여기에 의견 있으시면 편하게 말씀해주세요) @yudility

refactor: 커서 페이지네이션에서 사용하는 디코더와 인코더를 공통 유틸로 분리

---

init/schema.sql

- title_normalized 컬럼에 누락된 COLLATE "ko_KR.utf8" 옵션 추가
- data_id의 VARCHAR 대소문자 통일
COLLATE "ko_KR.utf8" 의 경우 데이터베이스에 ko_KR.utf8 로케일(한국어-대한민국의 UTF-8 인코딩 사용)이 설치되어 있지 않을 경우, 존재하지 않는다는 에러가 뜹니다. 때문에 로컬에서 사용할 땐 번거로우시더라도 제거한 후 사용하시거나 따로 로케일 설치하여 하시는 걸 추천드립니다!

chore: schema.sql 의 contents 테이블의 옵션 수정

---

src/main/java/team03/mopl/common/util/CursorCodecUtil.java
src/main/java/team03/mopl/domain/notification/NotificationEventListener.java
src/main/java/team03/mopl/domain/notification/entity/NotificationType.java
src/main/java/team03/mopl/domain/notification/events/FollowingPostedPlaylistEvent.java
src/main/java/team03/mopl/domain/notification/events/PlaylistSubscribedEvent.java
src/main/java/team03/mopl/domain/notification/events/PlaylistUpdatedEvent.java
src/main/java/team03/mopl/domain/notification/repository/NotificationRepository.java
src/main/java/team03/mopl/domain/notification/service/NotificationServiceImpl.java
src/main/java/team03/mopl/domain/playlist/service/PlaylistServiceImpl.java
src/main/java/team03/mopl/domain/subscription/service/SubscriptionServiceImpl.java
src/test/java/team03/mopl/domain/dm/repository/DmRepositoryCustomTest.java
src/test/java/team03/mopl/domain/notification/NotificationEventListenerTest.java
src/test/java/team03/mopl/domain/notification/service/NotificationServiceImplTest.java

- #223 
- 플레이리스트 업데이트 시 구독자에게 알림 전송
- 플레이리스트가 구독되면 플레이리스트 소유자에게 알림
- 플리 생성 시 플리 생성자를 팔로우하고 있던 팔로워에게 알림 전송
- 커서 페이징 유틸 사용으로 수정
- 이전 피드백 
- DmRepositoryCustomTest 의 QuerydslConfig 직접 생성해 쓰던 것 수정

feat: 각 도메인의 서비스 로직에 알림 기능 구현

---

src/main/java/team03/mopl/domain/content/batch/launcher/SportsJobScheduler.java
src/main/java/team03/mopl/domain/content/batch/sports/SportsApiProcessor.java
src/main/java/team03/mopl/domain/content/batch/sports/SportsApiReader.java
src/main/java/team03/mopl/domain/content/batch/sports/SportsBatchConfig.java
src/main/java/team03/mopl/domain/content/repository/ContentRepository.java

한국 시각 새벽 4시 → 오후 2시 ~ 6시의 30분 시각 마다
존재하는 컨텐츠일시 적재하지 않는다.
URL이 없다면 적재하지 않는다
스포츠 주기 적재 API의 yesterday 로그가 애플리케이션을 띄울 때 단 한 번만 발생하는 문제*
*빈 생성 주기와 관련: 애플리케이션이 시작될 때 모든 빈을 생성하는데, 이때 SportsApiReader 인스턴스를 생성하기 위해 생성자를 불러오면서 buildApiRequestInfo() 메소드를 호출한하기 때문에 발생한 문제
애플리케이션 시작시 로그가 찍히고, 스포츠 데이터 적재 잡이 실행될 땐 로그가 찍히지 않는다.
-> buildApiRequestInfo() 초기화: 생성자 → open() 메서드로 위치 변경
스포츠 데이터 적재 잡이 실행될 때 로그가 찍힌다.

refactor: 스포츠 컨텐츠 데이터 적재 시간 변경, 적재 규칙 변경, 로그 위치 수정

---

src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryImpl.java
src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
src/test/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryTest.java

- #231 
- 사용자와 시청방으로 조회 : FindByUserAndWatchRoomTest
- 유저가 특정 시청방에 참여중인지 확인 : ExistsWatchRoomParticipantByWatchRoomAndUserTest
- 검색 결과 총 개수 조회 : CountWatchRoomContentWithHeadcountDtoTest
- 시청방 정보  개별 조회 :  GetWatchRoomContentWithHeadcountDtoTest
- 검색 결과 페이지네이션 조회 : GetAllWatchRoomContentWithHeadcountDtoPaginatedTest
- 참여자수 기준 정렬 및 페이지네이션은 테스트할 때마다 성공/실패 여부가 달라져서 임시 주석처리하였습니다. 빠른시일내로 수정하겠습니다. 
- 참가자수 기준 페이지네이션 시 커서 적용을 having절로 하도록 수정

test: 시청방-사용자 레포지토리 테스트 코드 구현

---

src/main/java/team03/mopl/api/PlaylistApi.java
src/main/java/team03/mopl/common/exception/ErrorCode.java
src/main/java/team03/mopl/common/exception/curation/KeywordDeleteDeniedException.java
src/main/java/team03/mopl/common/exception/subscription/PrivatePlaylistSubscriptionException.java
src/main/java/team03/mopl/domain/playlist/controller/PlaylistController.java
src/main/java/team03/mopl/domain/playlist/repository/PlaylistRepository.java
src/main/java/team03/mopl/domain/playlist/service/PlaylistService.java
src/main/java/team03/mopl/domain/playlist/service/PlaylistServiceImpl.java
src/main/java/team03/mopl/domain/subscription/SubscriptionRepository.java
src/main/java/team03/mopl/domain/subscription/service/SubscriptionServiceImpl.java
src/test/java/team03/mopl/domain/playlist/PlaylistControllerTest.java
src/test/java/team03/mopl/domain/playlist/PlaylistServiceImplTest.java

- 전체 플레이리스트 조회하는 엔드포인트 로직 수정
- 사용자가 구독 중인 플레이리스트 조회하는 엔드포인트 수정

refactor: playlist 전체 조회 수정, 구독 조회 추가

---

ecs/task-definition.json

**task-definition**
- environment: AWS 오픈서치와 연결할 수 있는 엔드포인트를 환경변수(key-value)로 지정
- taskRoleArn: AWS 오픈서치에 HTTP 요청을 보낼 수 있도록 하는 컨테이너의 IAM역할 지정

chore: openSearch에 접근할 수 있도록 설정 추가

---

src/main/java/team03/mopl/common/config/AsyncConfig.java
src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java

fix: dmService의 자신이 보낸 메시지에 대해서 읽음처리

---

src/main/java/team03/mopl/domain/dm/controller/DmWebSocketController.java
src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
src/main/java/team03/mopl/domain/dm/service/PresenceTracker.java
src/test/java/team03/mopl/domain/dm/controller/DmWebSocketControllerTest.java
src/test/java/team03/mopl/domain/dm/service/DmServiceImplTest.java

- #274 
UserA와 UserB가 채팅방에 있을 때, UserB가 채팅방에 있음에도 불구하고 
UserA가 메시지를 보낼 때 UserB가 읽었음을 체크하지 못하는 현상 발생
```
@MessageMapping("/dmRooms/{roomId}/enter}")
public void enterRoom(@DestinationVariable String roomId, Principal principal) {
presenceTracker.enterRoom(principal.getName(),UUID.fromString(roomId));
log.info("enterRoom - 사용자 채팅방 접속: userName={}, roomId={}", principal.getName(), roomId);
}
@MessageMapping("/dmRooms/{roomId}/exit")
public void exitRoom(@DestinationVariable String roomId, Principal principal) {
presenceTracker.exitRoom(principal.getName(), UUID.fromString(roomId));
log.info("exitRoom - 사용자 채팅방 퇴장: userName={}, roomId={}", principal.getName(), roomId);
}
```
통신방에 들어올 때부터 Map<RoomId, UserId> 로 체크
들어와 있다면 sendDm 할 때 읽음 로직 포함해서 돌림

feat: 채팅방에 상대방 들어와 있을 때 읽음 처리 로직 추가

---

init/schema.sql
src/main/java/team03/mopl/domain/dm/dto/DmRoomDto.java
src/main/java/team03/mopl/domain/dm/entity/DmRoom.java
src/main/java/team03/mopl/domain/dm/service/DmRoomServiceImpl.java
src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
src/test/java/team03/mopl/domain/dm/controller/DmRoomControllerTest.java
src/test/java/team03/mopl/domain/dm/service/DmRoomServiceImplTest.java
src/test/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryTest.java

- #278 
- DmRoom 에 updatedAt 필드 추가
- 스키마 업데이트
- sendDm 시 updatedAt 수정 -> getAllRoomsForUser 시 최신 순으로 정렬

bug: dmRoom updatedAt 필드 추가 및 최신순 정렬

---

src/main/java/team03/mopl/common/util/CursorCodecUtil.java
src/main/java/team03/mopl/domain/dm/repository/DmRepository.java
src/main/java/team03/mopl/domain/dm/repository/DmRepositoryCustom.java
src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
src/test/java/team03/mopl/domain/dm/repository/DmRepositoryCustomTest.java
src/test/java/team03/mopl/domain/dm/service/DmServiceImplTest.java

- #280 
dm 페이징 시 CursorUtils의 엔코딩 수행하고 반환하도록 수정
- CursorCodecUtil 에 Dm 관련 encoding 로직 추가
- DmRepository 에서 dm.createdAt.lt -> dm.createdAt.loe
-  20개 요청 -> 21개까지 탐색 후 nextCursor 21번째 전달 -> 21번째부터 찾기
- CursorCodecUtil 를 통해 인코딩 후 반환하도록 수정

bug: dm encoding 추가

---

src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java

- 동일 사용자가 동일 콘텐츠에 리뷰 남겼을 때 예외처리가 이상하여 수정하였습니다

fix: 리뷰 중복 예외 처리 수정

---

src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java

- 시청방 중도 입장시 딜레이 발생하는 문제
- 예상 딜레이 시간 추가
- 테스트 코드 수정

fix: 시청방 예상 딜레이 시간 추가

---

src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java
src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java

fix: 시청방 예상 딜레이 시간 추가 main에 반영
