sb01-mopl-team03/sb01-mopl-team03

src/main/java/team03/mopl/domain/follow/entity/Follow.java, src/main/java/team03/mopl/domain/follow/repository/FollowRepository.java, src/main/java/team03/mopl/domain/follow/repository/UserRepository.java, src/main/java/team03/mopl/domain/follow/service/FollowService.java, src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java
=> feat: follow basic CRUD

src/main/java/team03/mopl/domain/follow/repository/UserRepository.java, src/main/java/team03/mopl/domain/review/dto/ReviewCreateRequest.java, src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java
실수로 수정안하고 머지해버려서 다시 PR 올립니다😂 죄송합니다
=> refactor: ReviewCreateRequest 수정, follow.userRepository 삭제

src/main/java/team03/mopl/domain/chat/dto/ChatRoomDto.java, src/main/java/team03/mopl/domain/dm/controller/DmController.java, src/main/java/team03/mopl/domain/dm/controller/DmRoomController.java, src/main/java/team03/mopl/domain/dm/entity/Dm.java, src/main/java/team03/mopl/domain/dm/entity/DmRoom.java, src/main/java/team03/mopl/domain/dm/service/DmRoomServiceImpl.java, src/main/java/team03/mopl/domain/follow/controller/FollowController.java, src/main/java/team03/mopl/domain/follow/dto/FollowRequest.java, src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java, src/main/java/team03/mopl/domain/notification/controller/NotificationController.java, src/main/java/team03/mopl/domain/notification/repository/NotificationRepository.java, src/main/java/team03/mopl/domain/notification/service/NotificationServiceImpl.java, src/test/java/team03/mopl/domain/dm/controller/DmControllerTest.java, src/test/java/team03/mopl/domain/dm/controller/DmRoomControllerTest.java, src/test/java/team03/mopl/domain/dm/service/DmRoomServiceImplTest.java, src/test/java/team03/mopl/domain/dm/service/DmServiceImplTest.java, src/test/java/team03/mopl/domain/follow/controller/FollowControllerTest.java, src/test/java/team03/mopl/domain/follow/service/FollowServiceImplTest.java, src/test/java/team03/mopl/domain/notification/controller/NotificationControllerTest.java, src/test/java/team03/mopl/domain/notification/service/NotificationServiceImplTest.java
- #48 
알림, 팔로우, DM 도메인 테스트 코드 작성
테스트 코드 실행 시 settings -> Build,Execution, Deployment -> build Tools -> Gradle 에서 빨간 줄 표시처럼 변경하면 됩니다!
findByReceiverIdAndRead -> findByReceiverIdAndIsRead
deleteRoom 로직 수정
FollowServiceImpl 내부 if( !followingId.equals(followerId) ) -> if( followingId.equals(followerId) )
=> feat: 알림, 팔로우, DM 테스트 코드 작성 및 오류 수정

init/schema.sql, src/main/java/team03/mopl/domain/content/Content.java, src/test/java/team03/mopl/domain/chat/service/ChatRoomServiceImplTest.java
- content 엔티티에 data_id 필드 추가 및 NoArgsConstructor 중복 제거
=> fix: db 스키마 변경

build.gradle, src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java, src/main/resources/models/cc.en.300.bin, src/main/resources/models/cc.ko.300.bin
- 한국어 분석을 위해 FastText 적용
- src/main/resources/models 경로에 model 추가
=> refactor: 한국어 처리 로직 강화

src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
=> chore: 사용하지 않는 import문 삭제

src/test/java/team03/mopl/domain/dm/controller/DmControllerTest.java, src/test/java/team03/mopl/domain/dm/controller/DmRoomControllerTest.java, src/test/java/team03/mopl/domain/follow/controller/FollowControllerTest.java, src/test/java/team03/mopl/domain/follow/service/FollowServiceImplTest.java, src/test/java/team03/mopl/domain/notification/controller/NotificationControllerTest.java, src/test/java/team03/mopl/domain/user/UserServiceImplTest.java
=> fix: 테스트 코드 수정

.github/workflows/test.yml
=> chore: test.yml에 최신 커밋 정보 로깅 기능 추가

src/test/java/team03/mopl/domain/review/ReviewControllerTest.java, src/test/java/team03/mopl/domain/review/ReviewServiceImplTest.java
- #61 
- review domain에 대한 service test, controller test 코드 추가
Close #61
=> feat: review service test, controller test 추가

build.gradle, src/main/java/team03/mopl/common/config/SecurityConfig.java, src/main/java/team03/mopl/common/config/SwaggerConfig.java
- API 문서화 작업 편의성을 위하여 추가하였습니다.
- application.yaml 에 관련 설정 추가하였습니다.
- SecurityConfig에 Swagger관련 URL은 모두 접근 가능하도록 하였습니다.
=> docs: swagger 의존성 추가 및 설정

src/main/java/team03/mopl/common/exception/ErrorCode.java, src/main/java/team03/mopl/domain/subscription/Subscription.java, src/main/java/team03/mopl/domain/subscription/service/SubscriptionServiceImpl.java, src/main/java/team03/mopl/domain/user/UserController.java, src/test/java/team03/mopl/domain/curation/CurationControllerTest.java, src/test/java/team03/mopl/domain/curation/CurationServiceImplTest.java, src/test/java/team03/mopl/domain/review/ReviewControllerTest.java
=> fix: 0710 merge 이후 에러 해결

src/main/java/team03/mopl/domain/watchroom/controller/WatchRoomController.java, src/test/java/team03/mopl/domain/watchroom/controller/WatchRoomControllerTest.java, src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java
- WatchRoomControllerTest 오류
- WatchRoom엔티티 필드 변경 적용하여 WatchRoomControllerTest 코드 수정
- WatchRoomController에서 아직 사용하지 않는 CustomUserDetails 파라미터 제거
=> fix: test 코드 수정 및 사용하지 않는 CustomUserDetails 파라미터 제거

src/test/java/team03/mopl/domain/review/ReviewControllerTest.java
=> fix: reviewControllerTest 오류 수정

src/main/java/team03/mopl/domain/curation/dto/KeywordDto.java
=> refactor: keywordId 필드 추가

src/main/java/team03/mopl/common/config/SecurityConfig.java, src/main/java/team03/mopl/storage/S3ProfileStorage.java
=> fix: acl 정책 제거, 시큐리티 예외처리

src/main/java/team03/mopl/common/dto/CursorPageResponseDto.java, src/main/java/team03/mopl/domain/dm/controller/DmController.java, src/main/java/team03/mopl/domain/dm/dto/DmPagingDto.java, src/main/java/team03/mopl/domain/dm/entity/Dm.java, src/main/java/team03/mopl/domain/dm/repository/DmRepositoryCustom.java, src/main/java/team03/mopl/domain/dm/service/DmService.java, src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java, src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java, src/main/java/team03/mopl/domain/notification/controller/NotificationController.java, src/main/java/team03/mopl/domain/notification/dto/NotificationDto.java, src/main/java/team03/mopl/domain/notification/dto/NotificationPagingDto.java, src/main/java/team03/mopl/domain/notification/repository/NotificationRepositoryCustom.java, src/main/java/team03/mopl/domain/notification/service/EmitterService.java, src/main/java/team03/mopl/domain/notification/service/NotificationService.java, src/main/java/team03/mopl/domain/notification/service/NotificationServiceImpl.java, src/test/java/team03/mopl/domain/dm/controller/DmControllerTest.java, src/test/java/team03/mopl/domain/dm/service/DmServiceImplTest.java, src/test/java/team03/mopl/domain/follow/controller/FollowControllerTest.java, src/test/java/team03/mopl/domain/notification/controller/NotificationControllerTest.java, src/test/java/team03/mopl/domain/notification/service/NotificationServiceImplTest.java
=> feat: 알림, DM 페이징 로직 구현

.github/workflows/deploy.yml
=> chore: deploy.yml 누락된 v 추가

.github/workflows/deploy.yml
=> merge: release 브랜치를 main 브랜치로 머지

ecs/task-definition.json
=> chore: task definition update

ecs/task-definition.json
=> chore: AWS task 메모리 및 cpu 할당량 수정

ecs/task-definition.json
=> chore: AWS task 메모리 및 cpu 할당량 수정 4vCPU -> 2vCPU

ecs/task-definition.json
=> chore: AWS task 메모리 할당량 수정  2vCPU, 8192MB -> 3vCPU, 4096MB

.github/workflows/deploy.yml, build.gradle, ecs/task-definition.json
=> hotfix: build.gradle 충돌 해결

src/main/java/team03/mopl/domain/playlist/dto/AddContentsRequest.java
- AddContentsRequest에서 validation message 수정 (음악 ID -> 콘텐츠 ID)
=> refactor: validation message 수정

ecs/task-definition.json
=> hotfix: 메모리 1기가로 설정 후 상태확인

ecs/task-definition.json, src/main/java/team03/mopl/domain/playlist/dto/AddContentsRequest.java
=> hotfix: 메모리 2기가로 낮춘 뒤 상태 확인

ecs/task-definition.json
hotfix: CPU 2GB, 메모리 2GB 로 수정 후 상태 확인
=> hotfix: CPU 2GB, 메모리 2GB 로 수정 후 상태 확인

ecs/task-definition.json
=> chore: healthCheck command 추가

docker-compose.yml
"" 따옴표로 일관성을 맞췄습니다.
push는 되었는데 어째서인지 PR에는 등록이 안됐어서 다시 올려놓습니다!
=> chore: docker compose 일부 수정

src/main/java/team03/mopl/domain/content/dto/ContentDto.java
- @Schema를 통해 description 작성
- [] 코드가 정상적으로 컴파일되나요?
=> fix: ContentDto.java에 쉼표 추가

src/main/java/team03/mopl/common/config/AsyncConfig.java, src/main/java/team03/mopl/common/config/SecurityConfig.java, src/main/java/team03/mopl/domain/notification/repository/EmitterRepositoryImpl.java, src/main/java/team03/mopl/domain/notification/service/EmitterService.java
1. App.tsx에서 토큰 갱신: 30초마다 토큰 만료를 체크해서 자동으로 새 토큰을 발급받습니다
2. SSE 연결의 문제: Header.tsx의 SSE 연결은 처음 연결할 때의 토큰을 계속 사용하고, 토큰이 갱신되어도 SSE 연결을 다시 생성하지 않습니다
3. 10분 후 AccessDenied: JWT 토큰이 10분 유효기간을 가지고 있고, SSE 연결이 만료된 토큰을 계속 사용해서 백엔드에서 인증 오류가 발생합니다
4. Spring Security와 SSE 충돌
- SSE는 비동기 스트림 처리
- Spring Security는 동기적 Authorization 확인
- 둘이 충돌하여 응답이 커밋된 후 보안 예외 발생
현재는 AccessDenied 문제와 "Response not usable after response errors" 문제는 해결되었지만 1초에 한 번씩 SSE 연결을 진행하고 있어 수정해야 함
=> fix: sse access denied 수정

src/main/java/team03/mopl/domain/follow/controller/FollowController.java, src/test/java/team03/mopl/domain/follow/controller/FollowControllerTest.java
- 팔로우: POST /api/follows/follow ->  POST /api/follow
- 언팔로우: DELETE /api/follows/unfollow  ->  DELETE /api/follows
=> refactor: follow 기능 엔드포인트 수정

src/main/java/team03/mopl/common/exception/GlobalExceptionHandler.java
=> feat: 예외 처리

src/main/java/team03/mopl/domain/user/UserController.java, src/main/java/team03/mopl/domain/user/UserCreateRequest.java, src/main/java/team03/mopl/domain/user/UserServiceImpl.java, src/main/java/team03/mopl/domain/user/UserUpdateRequest.java, src/test/java/team03/mopl/domain/user/UserControllerTest.java, src/test/java/team03/mopl/domain/user/UserServiceImplTest.java
=> refactor: 비밀번호 패턴 적용

build.gradle, docker-compose.yml, src/main/java/team03/mopl/MoplApplication.java, src/main/java/team03/mopl/common/config/AWSRequestSigningApacheInterceptor.java, src/main/java/team03/mopl/common/config/SearchEngineConfig.java
=> fix: open search config 변경

src/main/java/team03/mopl/common/config/SearchEngineConfig.java
=> fix: searchEngineConfig 수정2

src/main/java/team03/mopl/common/config/SearchEngineConfig.java
=> fix: searchEngineConfig 수정3

src/main/java/team03/mopl/common/config/SearchEngineConfig.java
=> fix: searchEngineConfig 수정4

src/main/resources/application-prod.yaml
=> fix: redirect-uri 수정

src/main/java/team03/mopl/common/config/SearchEngineConfig.java, src/main/resources/application-prod.yaml
=> merge main

build.gradle, src/main/java/team03/mopl/common/config/ElasticsearchConfig.java, src/main/java/team03/mopl/common/config/OpensearchRestClientConfiguration.java, src/main/java/team03/mopl/domain/curation/elasticsearch/ContentSearch.java
=> fix: aws elasticsearch config 수정

build.gradle, src/main/java/team03/mopl/common/config/OpenSearchConfig.java, src/main/java/team03/mopl/common/config/OpensearchRestClientConfiguration.java
=> fix: opensearch config 수정

src/main/java/team03/mopl/common/config/SecurityConfig.java, src/main/java/team03/mopl/jwt/MemoryJwtBlacklist.java, src/main/java/team03/mopl/jwt/RedisJwtBlacklist.java
=> refactor: 공유페이지, 플레이리스트 제외

build.gradle, src/main/java/team03/mopl/common/interceptor/WebSocketAuthInterceptor.java, src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomMessageRepository.java, src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryImpl.java, src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java, src/test/java/team03/mopl/common/interceptor/WebSocketAuthInterceptorTest.java, src/test/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryTest.java, src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java
=> fix: 시청방 오류, 테스트 코드 수정 및 테스트 리포트 제외 항목 추가

init/schema.sql, src/main/java/team03/mopl/domain/dm/entity/DmRoom.java, src/main/java/team03/mopl/domain/dm/repository/DmRepositoryCustom.java, src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java, src/test/java/team03/mopl/domain/dm/repository/DmRepositoryCustomTest.java
- #285 
Dm cursor 페이징 로직 수정
- dm.createdAt.**lt**(mainCursorDate).or(dm.createdAt.eq(mainCursorDate).and(dm.id.lt(subCursorId)));
- 스키마 수정
- dmRoom 엔티티 필드의 @Column(name = "last_message_at") 수정
- hasNext는 size()+1 [ex: 20+1]로 확인하고 출력할 마지막 값을 전달 ( size()-2 ) [19] 
- 다음 출력 시작은 현재 기준 size()-1 [20] 부터
```
if (hasNext) {
//더 보낼게 있는 것들
DmDto lastDmDto = dmDtoList.get(dmDtoList.size() - 2);
nextCursor = cursorCodecUtil.encodeNextCursor(lastDmDto);
dmDtoList = dmDtoList.subList(0, size);//20개가 넘치니 자름
}
```
=> bug: dm Cursor 페이징 로직 수정

src/main/java/team03/mopl/common/config/CorsConfig.java, src/main/java/team03/mopl/common/config/SecurityConfig.java
=> fix: /login 리소스 접근 불가로 수정

src/main/resources/application-prod.yaml
=> fix: oauth 로그인 프론트 redirect url 주소 수정

src/main/java/team03/mopl/domain/oauth2/OAuth2SuccessHandler.java
=> fix: 재 로그인시 세션 제거

src/main/java/team03/mopl/domain/oauth2/OAuth2SuccessHandler.java, src/main/resources/application-prod.yaml
=> 재 로그인 시 세션 제거

src/main/java/team03/mopl/common/config/SecurityConfig.java, src/main/java/team03/mopl/domain/oauth2/OAuth2FailureHandler.java
=> feat: 소셜 로그인 실패 로그

src/main/java/team03/mopl/domain/auth/AuthController.java, src/main/java/team03/mopl/domain/auth/CookieUtil.java, src/main/java/team03/mopl/domain/oauth2/OAuth2SuccessHandler.java
=> refactor: 쿠기 설정

src/main/java/team03/mopl/domain/auth/AuthController.java, src/main/java/team03/mopl/domain/auth/CookieUtil.java, src/main/java/team03/mopl/domain/oauth2/OAuth2SuccessHandler.java
=> fix: 반환값 수정

src/main/resources/application-prod.yaml
=> fix: oauth 로그인 카카오 secret 키 제거

src/test/java/team03/mopl/domain/auth/AuthControllerTest.java
=> refactor: 빈 추가

src/main/java/team03/mopl/api/NotificationApi.java, src/main/java/team03/mopl/domain/dm/service/DmRoomServiceImpl.java, src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java, src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java, src/main/java/team03/mopl/domain/notification/NotificationEventListener.java, src/main/java/team03/mopl/domain/notification/controller/NotificationController.java, src/main/java/team03/mopl/domain/notification/dto/NotificationDto.java, src/main/java/team03/mopl/domain/notification/service/NotificationService.java, src/main/java/team03/mopl/domain/notification/service/NotificationServiceImpl.java, src/test/java/team03/mopl/domain/dm/controller/DmWebSocketControllerTest.java, src/test/java/team03/mopl/domain/notification/controller/NotificationControllerTest.java, src/test/java/team03/mopl/domain/notification/service/NotificationServiceImplTest.java
- #316 
단일 알림 읽음 엔드포인트 추가 및 테스트 코드 추가
```
@PostMapping("/{notificationId}")
public ResponseEntity<Void> readNotification(@PathVariable UUID notificationId, @AuthenticationPrincipal CustomUserDetails user) {
UUID userId = user.getId();
notificationService.readNotification(userId, notificationId);
return ResponseEntity.ok().build();
}
```
알림 모두 읽기 엔드포인트 추가
```
@PostMapping("/")
public ResponseEntity<Void> readAllNotification(@AuthenticationPrincipal CustomUserDetails user) {
UUID userId = user.getId();
notificationService.markAllAsRead(userId);
return ResponseEntity.ok().build();
}
```
- Notification API 추가
- DmWebSocketControllerTest 에 테스트 코드 추가
- Dm 채팅방 출입할 때 엔드포인트 추가한 것들 테스트 코드
=> feat: 단일 알림 읽음 처리, API 추가, 테스트 코드 추가

src/test/java/team03/mopl/domain/curation/ContentSearchServiceTest.java, src/test/java/team03/mopl/domain/curation/CurationServiceTest.java
- ContentSearchServiceTest 코드 생성
=> test: contentSearchTest 코드 생성

src/main/java/team03/mopl/common/config/CorsConfig.java
=> hotfix:  프론트 주소 변경으로 인한 CORS 설정 추가

src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java
=> bug: notification-follow
